name: flutter_tex_example
description: A Flutter Package (Demo) to render LaTeX with full HTML and JavaScript support.
homepage: https://github.com/shahxadakram/flutter_tex

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex:
    path: ../
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/flutter_tex_banner.png