name: flutter_tex_example
description: A Flutter Package (Demo) to render LaTeX with full HTML and JavaScript support.
homepage: https://github.com/shahxadakram/flutter_tex

version: 3.6.7

publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tex:
    path: ../
  webview_flutter_web: ^0.2.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_tex_banner.png
    - assets/fonts/Army.ttf
    - assets/fonts/Budhrg.ttf
    - assets/fonts/CELTG.ttf
    - assets/fonts/hillock.ttf
    - assets/fonts/intimacy.ttf
    - assets/fonts/SansationLight.ttf
    - assets/fonts/slenmini.ttf
    - assets/fonts/SubaccuzRegular.ttf
